
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CLOSE FGL IF IMPORT NOT_EQL OPEN QUOTE STATE ST_CLIENT_STATE THEN\n        starter : versioning_check \n                | import\n        \n        import : IMPORT FGL\n        \n        versioning_check : IF OPEN inner_check CLOSE THEN\n        \n        not_state : ST_CLIENT_STATE NOT_EQL QUOTE STATE QUOTE\n        \n        inner_check : not_state AND not_state AND not_state AND not_state AND not_state AND not_state AND not_state AND not_state AND not_state\n        '
    
_lr_action_items = {'IF':([0,],[4,]),'IMPORT':([0,],[5,]),'$end':([1,2,3,7,14,],[0,-1,-2,-3,-4,]),'OPEN':([4,],[6,]),'FGL':([5,],[7,]),'ST_CLIENT_STATE':([6,12,17,21,23,25,27,29,31,],[10,10,10,10,10,10,10,10,10,]),'CLOSE':([8,20,32,],[11,-5,-6,]),'AND':([9,15,19,20,22,24,26,28,30,],[12,17,21,-5,23,25,27,29,31,]),'NOT_EQL':([10,],[13,]),'THEN':([11,],[14,]),'QUOTE':([13,18,],[16,20,]),'STATE':([16,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'starter':([0,],[1,]),'versioning_check':([0,],[2,]),'import':([0,],[3,]),'inner_check':([6,],[8,]),'not_state':([6,12,17,21,23,25,27,29,31,],[9,15,19,22,24,26,28,30,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> starter","S'",1,None,None,None),
  ('starter -> versioning_check','starter',1,'p_starter','parse',101),
  ('starter -> import','starter',1,'p_starter','parse',102),
  ('import -> IMPORT FGL','import',2,'p_import','parse',107),
  ('versioning_check -> IF OPEN inner_check CLOSE THEN','versioning_check',5,'p_versioning_check','parse',115),
  ('not_state -> ST_CLIENT_STATE NOT_EQL QUOTE STATE QUOTE','not_state',5,'p_not_state','parse',123),
  ('inner_check -> not_state AND not_state AND not_state AND not_state AND not_state AND not_state AND not_state AND not_state AND not_state','inner_check',17,'p_inner_check','parse',128),
]
